import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BooksA'Natural",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Meta tags, link tags, etc., if any */}
      </head>
      <body className={inter.className}>
        <header>BooksA'Natural</header>
        {children}
      </body>
    </html>
  );
}
